## This workbook demonstrates the applicability of Data analysis on a dataset.

Here we consider the dataset pertaininig to a fictional online shoe-store and highlights its customer information.

In [22]:
import numpy as np
import pandas as pd
import os

In [23]:
os.listdir()
orders=pd.read_csv('shoefly.csv')

Now, we check the first few lines of 'SHOEFLY' company's data.

In [24]:
print(orders.head())
print(orders.info())

      id first_name last_name  gender                         email  \
0  54791    Rebecca   Lindsay  female  RebeccaLindsay57@hotmail.com
1  53450      Emily     Joyce  female        EmilyJoyce25@gmail.com
2  91987      Joyce    Waller  female        Joyce.Waller@gmail.com
3  14437     Justin  Erickson    male   Justin.Erickson@outlook.com
4  79357     Andrew     Banks    male              AB4318@gmail.com

      shoe_type shoe_material shoe_color
0         clogs  faux-leather      black
1  ballet flats  faux-leather       navy
2       sandles        fabric      black
3         clogs  faux-leather        red
4         boots       leather      brown
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             20 non-null     int64
 1   first_name     20 non-null     object
 2   last_name      20 non-null     object
 3   gender         20 non-null     object
 4   email          20 non-null     object
 5   shoe_type      20 non-null     object
 6   shoe_material  20 non-null     object
 7   shoe_color     20 non-null     object
dtypes: int64(1), object(7)
memory usage: 1.4+ KB
None

Here we select all the email addresses present for our mkt dept to shoot out emails to.

In [25]:
emails=orders.email
emails

0     RebeccaLindsay57@hotmail.com
1           EmilyJoyce25@gmail.com
2           Joyce.Waller@gmail.com
3      Justin.Erickson@outlook.com
4                 AB4318@gmail.com
5           JulieMarsh59@gmail.com
6                 TJ5470@gmail.com
7           Janice.Hicks@gmail.com
8        GabrielPorter24@gmail.com
9        FrancesPalmer50@gmail.com
10         JessicaHale25@gmail.com
11      LawrenceParker44@gmail.com
12         SusanDennis58@gmail.com
13                DO2680@gmail.com
14       Rebecca.Charles@gmail.com
15              JC2072@hotmail.com
16              VS4753@outlook.com
17          RoyTillman20@gmail.com
18       Thomas.Roberson@gmail.com
19         ANewton1977@outlook.com
Name: email, dtype: object

Here, we select order of a person named 'francis palmer' since her order was wrong.

In [26]:
frances_palmer=orders[(orders.first_name=='Frances')&(orders.last_name=='Palmer')]
print(frances_palmer)

      id first_name last_name  gender                      email shoe_type  \
9  62083    Frances    Palmer  female  FrancesPalmer50@gmail.com    wedges

  shoe_material shoe_color
9       leather      white

Now, we select those shoes that are deemed comfortable to provide rating to by customers.

In [27]:
comfy_shoes=orders[orders.shoe_type.isin(['clogs','boots','ballet flats'])]

Here, we create a seperate column indicating the email provider's names

In [28]:
orders['provider']=orders.email.apply(lambda x:x.split('@')[-1])
orders

,id,first_name,last_name,gender,email,shoe_type,shoe_material,shoe_color,provider
0,54791,Rebecca,Lindsay,female,RebeccaLindsay57@hotmail.com,clogs,faux-leather,black,hotmail.com
1,53450,Emily,Joyce,female,EmilyJoyce25@gmail.com,ballet flats,faux-leather,navy,gmail.com
2,91987,Joyce,Waller,female,Joyce.Waller@gmail.com,sandles,fabric,black,gmail.com
3,14437,Justin,Erickson,male,Justin.Erickson@outlook.com,clogs,faux-leather,red,outlook.com
4,79357,Andrew,Banks,male,AB4318@gmail.com,boots,leather,brown,gmail.com
5,52386,Julie,Marsh,female,JulieMarsh59@gmail.com,sandles,fabric,black,gmail.com
6,20487,Thomas,Jensen,male,TJ5470@gmail.com,clogs,fabric,navy,gmail.com
7,76971,Janice,Hicks,female,Janice.Hicks@gmail.com,clogs,faux-leather,navy,gmail.com
8,21586,Gabriel,Porter,male,GabrielPorter24@gmail.com,clogs,leather,brown,gmail.com
9,62083,Frances,Palmer,female,FrancesPalmer50@gmail.com,wedges,leather,white,gmail.com
10,91629,Jessica,Hale,female,JessicaHale25@gmail.com,clogs,leather,red,gmail.com
11,98602,Lawrence,Parker,male,LawrenceParker44@gmail.com,wedges,fabric,brown,gmail.com
12,45832,Susan,Dennis,female,SusanDennis58@gmail.com,ballet flats,fabric,white,gmail.com
13,33862,Diane,Ochoa,female,DO2680@gmail.com,sandles,fabric,red,gmail.com
14,73431,Rebecca,Charles,female,Rebecca.Charles@gmail.com,boots,faux-leather,white,gmail.com
15,93889,Jacqueline,Crane,female,JC2072@hotmail.com,wedges,fabric,red,hotmail.com
16,39888,Vincent,Stephenson,male,VS4753@outlook.com,boots,leather,black,outlook.com
17,35961,Roy,Tillman,male,RoyTillman20@gmail.com,boots,leather,white,gmail.com
18,24560,Thomas,Roberson,male,Thomas.Roberson@gmail.com,wedges,fabric,red,gmail.com
19,28559,Angela,Newton,female,ANewton1977@outlook.com,wedges,fabric,red,outlook.com

Now suppose we add a new column the value of which depends on columns that already exists. Here we apply lambda functions on rows that spans multiple columns.

In [29]:
orders['shoe_source']=orders.shoe_material.apply(lambda x:'animal' if x == 'leather' else 'vegan')
orders.head()

,id,first_name,last_name,gender,email,shoe_type,shoe_material,shoe_color,provider,shoe_source
0,54791,Rebecca,Lindsay,female,RebeccaLindsay57@hotmail.com,clogs,faux-leather,black,hotmail.com,vegan
1,53450,Emily,Joyce,female,EmilyJoyce25@gmail.com,ballet flats,faux-leather,navy,gmail.com,vegan
2,91987,Joyce,Waller,female,Joyce.Waller@gmail.com,sandles,fabric,black,gmail.com,vegan
3,14437,Justin,Erickson,male,Justin.Erickson@outlook.com,clogs,faux-leather,red,outlook.com,vegan
4,79357,Andrew,Banks,male,AB4318@gmail.com,boots,leather,brown,gmail.com,animal

Now we create a column that indicates salutation to use when shooting mail to respective customers.

In [31]:
orders['salutation']=orders.apply(lambda row:'Dear Mr. '+row['last_name'] if row['gender']=='male' else 'Dear Ms. '+row['last_name'],axis=1)
orders.head()

,id,first_name,last_name,gender,email,shoe_type,shoe_material,shoe_color,provider,shoe_source,salutation
0,54791,Rebecca,Lindsay,female,RebeccaLindsay57@hotmail.com,clogs,faux-leather,black,hotmail.com,vegan,Dear Ms. Lindsay
1,53450,Emily,Joyce,female,EmilyJoyce25@gmail.com,ballet flats,faux-leather,navy,gmail.com,vegan,Dear Ms. Joyce
2,91987,Joyce,Waller,female,Joyce.Waller@gmail.com,sandles,fabric,black,gmail.com,vegan,Dear Ms. Waller
3,14437,Justin,Erickson,male,Justin.Erickson@outlook.com,clogs,faux-leather,red,outlook.com,vegan,Dear Mr. Erickson
4,79357,Andrew,Banks,male,AB4318@gmail.com,boots,leather,brown,gmail.com,animal,Dear Mr. Banks